### ISSUE TITLE
Support for Soundbar 500/700

### ISSUE THREAD

**Issue by Hiffi** [iobroker-community-adapters/ioBroker.bosesoundtouch#26]
Hi,
is there a plan to support the new products of bose?

I have the Soundbar 700 & Bass Module 700 with Alexa integration. And since the soundbar can control all my other devices (tv, receiver, bluray player). It would be nice to have a single adapter to control them all.

**Comment by scheilch** [comment]
What you want is a mutli device remote as an adapter. That won‘t be realized. You have a Remote control with thousands of different infrared commands. Do you want to implement them all?

**Comment by Hiffi** [comment]
No, that's not what I meant.

Bose released a new product series. By now it's the Bose soundbar 500, soundbar 700 and home speaker 500. Sadly the products are not compatible with the Soundtouch series.

There are 3 ways to control the devices:
1. Via Bose music app (iOS, android)
2. RF remote control
3. Alexa voice control

It would be nice, if I could control my Bose soundbar 700 over iobroker, too. It would work in the same way like the Soundtouch series (pause,play,next, previous,power on, power off,...)
That's my basic request.

A second idea is the control of other devices. The remote control works via RF and not via IR. The soundbar itself sends the IR signal to the other devices. For example, can I change my TV channels with the same remote control over the soundbar. I don't now, if it is possible to trigger the IR signal via iobroker. I don't want to control the many different devices, I want to trigger the pre-programmed IR signals in the soundbar.

**Comment by JoJ123** [comment]
We could think about the first thing, to control also the new devices with the same adapter.
But first I would like to change the adapter in the way, that there is just one adapter for all the speakers in one home.
