### ISSUE TITLE
js-controller 3.2.16

### ISSUE THREAD

**Issue by michi-68** [iobroker-community-adapters/ioBroker.bosesoundtouch#51]
Nach dem update auf js-controller 3.2.16 kommen folgende Warnungen

bosesoundtouch.0	2021-02-26 20:16:58.886	warn	(10402) State "bosesoundtouch.0.sources.LOCAL_INTERNET_RADIO" has no existing object, this might lead to an error in future versions
bosesoundtouch.0	2021-02-26 20:16:58.884	warn	(10402) State "bosesoundtouch.0.sources.TUNEIN" has no existing object, this might lead to an error in future versions
bosesoundtouch.0	2021-02-26 20:16:58.883	warn	(10402) State "bosesoundtouch.0.sources.ALEXA" has no existing object, this might lead to an error in future versions
bosesoundtouch.0	2021-02-26 20:16:58.881	warn	(10402) State "bosesoundtouch.0.sources.AMAZON" has no existing object, this might lead to an error in future versions
bosesoundtouch.0	2021-02-26 20:16:58.879	warn	(10402) State "bosesoundtouch.0.sources.AUX" has no existing object, this might lead to an error in future versions

Platform: linux
os: Raspbian GNU/Linux 10 (buster)
Architecture: arm
CPUs: 4
Speed: 1500 MHz
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.7 GB 
Node.js: v12.21.0
NPM: 6.14.11

**Comment by santa81** [comment]
und mit js 3.3.x

bosesoundtouch.0 | 2021-05-04 21:46:30.165 | info | State value to set for "bosesoundtouch.0.volume" has to be type "number" but received type "string"
-- | -- | -- | --
bosesoundtouch.0 | 2021-05-04 21:46:30.164 | info | State value to set for "bosesoundtouch.0.nowPlaying.time" has to be type "number" but received type "string"
bosesoundtouch.0 | 2021-05-04 21:46:30.162 | info | State value to set for "bosesoundtouch.0.nowPlaying.total" has to be type "number" but received type "string"

**Comment by Apollon77** [comment]
Please try Github version. Update from Github, restart adapter manually ...  and check please if errors are gone

**Comment by santa81** [comment]
Mit 0.10.0 ist alles ok. Kann geschlossen werden.
