### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.bosesoundtouch#8]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by Apollon77** [comment]
What exactly help is needed?

**Comment by SwedishChef** [comment]
@Apollon77 
is this still a topic or can it be close with version 0.9.3?

BTW: I need some developer that takes over maintaining this adapter code as I personally no longer use ioBroker. Any Idea?

**Comment by Apollon77** [comment]
Yes, still current, maybe hand over all your adapters into the adapter-community? https://github.com/iobroker-community-adapters/info

**Comment by mcm1957** [comment]
outdated
